name: Publish to pub.dev
on:
  push:
    tags:
      - rel/*
jobs:
  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIALS_JSON }}
          format: true
          force: true
